// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: snake_server.proto
#ifndef GRPC_snake_5fserver_2eproto__INCLUDED
#define GRPC_snake_5fserver_2eproto__INCLUDED

#include "snake_server.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace examples {
namespace grpc_server {

class SnakeService final {
 public:
  static constexpr char const* service_full_name() {
    return "examples.grpc_server.SnakeService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status EatGold(::grpc::ClientContext* context, const ::examples::grpc_server::EnclaveInput& request, ::examples::grpc_server::EnclaveOutput* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::examples::grpc_server::EnclaveOutput>> AsyncEatGold(::grpc::ClientContext* context, const ::examples::grpc_server::EnclaveInput& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::examples::grpc_server::EnclaveOutput>>(AsyncEatGoldRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::examples::grpc_server::EnclaveOutput>> PrepareAsyncEatGold(::grpc::ClientContext* context, const ::examples::grpc_server::EnclaveInput& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::examples::grpc_server::EnclaveOutput>>(PrepareAsyncEatGoldRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void EatGold(::grpc::ClientContext* context, const ::examples::grpc_server::EnclaveInput* request, ::examples::grpc_server::EnclaveOutput* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::examples::grpc_server::EnclaveOutput>* AsyncEatGoldRaw(::grpc::ClientContext* context, const ::examples::grpc_server::EnclaveInput& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::examples::grpc_server::EnclaveOutput>* PrepareAsyncEatGoldRaw(::grpc::ClientContext* context, const ::examples::grpc_server::EnclaveInput& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status EatGold(::grpc::ClientContext* context, const ::examples::grpc_server::EnclaveInput& request, ::examples::grpc_server::EnclaveOutput* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::examples::grpc_server::EnclaveOutput>> AsyncEatGold(::grpc::ClientContext* context, const ::examples::grpc_server::EnclaveInput& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::examples::grpc_server::EnclaveOutput>>(AsyncEatGoldRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::examples::grpc_server::EnclaveOutput>> PrepareAsyncEatGold(::grpc::ClientContext* context, const ::examples::grpc_server::EnclaveInput& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::examples::grpc_server::EnclaveOutput>>(PrepareAsyncEatGoldRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void EatGold(::grpc::ClientContext* context, const ::examples::grpc_server::EnclaveInput* request, ::examples::grpc_server::EnclaveOutput* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::examples::grpc_server::EnclaveOutput>* AsyncEatGoldRaw(::grpc::ClientContext* context, const ::examples::grpc_server::EnclaveInput& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::examples::grpc_server::EnclaveOutput>* PrepareAsyncEatGoldRaw(::grpc::ClientContext* context, const ::examples::grpc_server::EnclaveInput& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_EatGold_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status EatGold(::grpc::ServerContext* context, const ::examples::grpc_server::EnclaveInput* request, ::examples::grpc_server::EnclaveOutput* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_EatGold : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_EatGold() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_EatGold() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EatGold(::grpc::ServerContext* context, const ::examples::grpc_server::EnclaveInput* request, ::examples::grpc_server::EnclaveOutput* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEatGold(::grpc::ServerContext* context, ::examples::grpc_server::EnclaveInput* request, ::grpc::ServerAsyncResponseWriter< ::examples::grpc_server::EnclaveOutput>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_EatGold<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_EatGold : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_EatGold() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ExperimentalWithCallbackMethod_EatGold<BaseClass>, ::examples::grpc_server::EnclaveInput, ::examples::grpc_server::EnclaveOutput>(
          [this](::grpc::ServerContext* context,
                 const ::examples::grpc_server::EnclaveInput* request,
                 ::examples::grpc_server::EnclaveOutput* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->EatGold(context, request, response, controller);
                 }, this));
    }
    ~ExperimentalWithCallbackMethod_EatGold() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EatGold(::grpc::ServerContext* context, const ::examples::grpc_server::EnclaveInput* request, ::examples::grpc_server::EnclaveOutput* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void EatGold(::grpc::ServerContext* context, const ::examples::grpc_server::EnclaveInput* request, ::examples::grpc_server::EnclaveOutput* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_EatGold<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_EatGold : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_EatGold() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_EatGold() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EatGold(::grpc::ServerContext* context, const ::examples::grpc_server::EnclaveInput* request, ::examples::grpc_server::EnclaveOutput* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_EatGold : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_EatGold() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_EatGold() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EatGold(::grpc::ServerContext* context, const ::examples::grpc_server::EnclaveInput* request, ::examples::grpc_server::EnclaveOutput* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEatGold(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_EatGold : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_EatGold() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ExperimentalWithRawCallbackMethod_EatGold<BaseClass>, ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->EatGold(context, request, response, controller);
                 }, this));
    }
    ~ExperimentalWithRawCallbackMethod_EatGold() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EatGold(::grpc::ServerContext* context, const ::examples::grpc_server::EnclaveInput* request, ::examples::grpc_server::EnclaveOutput* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void EatGold(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_EatGold : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_EatGold() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::examples::grpc_server::EnclaveInput, ::examples::grpc_server::EnclaveOutput>(std::bind(&WithStreamedUnaryMethod_EatGold<BaseClass>::StreamedEatGold, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_EatGold() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status EatGold(::grpc::ServerContext* context, const ::examples::grpc_server::EnclaveInput* request, ::examples::grpc_server::EnclaveOutput* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedEatGold(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::examples::grpc_server::EnclaveInput,::examples::grpc_server::EnclaveOutput>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_EatGold<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_EatGold<Service > StreamedService;
};

}  // namespace grpc_server
}  // namespace examples


#endif  // GRPC_snake_5fserver_2eproto__INCLUDED
