/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef SNAKE_ARGS_H
#define SNAKE_ARGS_H

#include <stdint.h>
#include <stdlib.h> /* for wchar_t */ 

#include <openenclave/bits/result.h>

#include "snake.h"

typedef struct _eat_gold_args_t {
    oe_result_t _result;
	int _retval;
	snake_t* snake;
	screen_t* screen;
 } eat_gold_args_t;

/* trusted function ids */
enum {
    fcn_id_eat_gold = 0,
    fcn_id_trusted_call_id_max = OE_ENUM_MAX
};


/* untrusted function ids */
enum {
    fcn_id_untrusted_call_max = OE_ENUM_MAX
};


#endif // SNAKE_ARGS_H
