/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#include "sgx_t.h"
#include <openenclave/edger8r/enclave.h>
#include <stdlib.h>
#include <string.h>
#include <wchar.h>

OE_EXTERNC_BEGIN



/****** ECALL function wrappers  *************/
void ecall_setup_level_protected(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters */
    setup_level_protected_args_t* pargs_in = (setup_level_protected_args_t*) input_buffer;
    setup_level_protected_args_t* pargs_out = (setup_level_protected_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers */
    OE_SET_IN_OUT_POINTER(screen, sizeof(screen_t));
    OE_SET_IN_OUT_POINTER(snake, sizeof(snake_t));

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */
    OE_COPY_AND_SET_IN_OUT_POINTER(screen, sizeof(screen_t));
    OE_COPY_AND_SET_IN_OUT_POINTER(snake, sizeof(snake_t));

    /* Check that in/in-out strings are null terminated */

    /* lfence after checks */
    oe_lfence();

    /* Call user function */
    setup_level_protected(
        pargs_in->screen,
        pargs_in->snake,
        pargs_in->level);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ecall_move_protected(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters */
    move_protected_args_t* pargs_in = (move_protected_args_t*) input_buffer;
    move_protected_args_t* pargs_out = (move_protected_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers */
    OE_SET_IN_OUT_POINTER(snake, sizeof(snake_t));
    OE_SET_IN_OUT_POINTER(keys, sizeof(char));

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */
    OE_COPY_AND_SET_IN_OUT_POINTER(snake, sizeof(snake_t));
    OE_COPY_AND_SET_IN_OUT_POINTER(keys, sizeof(char));

    /* Check that in/in-out strings are null terminated */

    /* lfence after checks */
    oe_lfence();

    /* Call user function */
    move_protected(
        pargs_in->snake,
        pargs_in->keys,
        pargs_in->key);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ecall_collide_object_protected(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters */
    collide_object_protected_args_t* pargs_in = (collide_object_protected_args_t*) input_buffer;
    collide_object_protected_args_t* pargs_out = (collide_object_protected_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers */
    OE_SET_IN_OUT_POINTER(snake, sizeof(snake_t));
    OE_SET_IN_OUT_POINTER(screen, sizeof(screen_t));

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */
    OE_COPY_AND_SET_IN_OUT_POINTER(snake, sizeof(snake_t));
    OE_COPY_AND_SET_IN_OUT_POINTER(screen, sizeof(screen_t));

    /* Check that in/in-out strings are null terminated */

    /* lfence after checks */
    oe_lfence();

    /* Call user function */
    pargs_out->_retval = collide_object_protected(
        pargs_in->snake,
        pargs_in->screen,
        pargs_in->object);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ecall_collision_protected(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters */
    collision_protected_args_t* pargs_in = (collision_protected_args_t*) input_buffer;
    collision_protected_args_t* pargs_out = (collision_protected_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers */
    OE_SET_IN_OUT_POINTER(snake, sizeof(snake_t));
    OE_SET_IN_OUT_POINTER(screen, sizeof(screen_t));

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */
    OE_COPY_AND_SET_IN_OUT_POINTER(snake, sizeof(snake_t));
    OE_COPY_AND_SET_IN_OUT_POINTER(screen, sizeof(screen_t));

    /* Check that in/in-out strings are null terminated */

    /* lfence after checks */
    oe_lfence();

    /* Call user function */
    pargs_out->_retval = collision_protected(
        pargs_in->snake,
        pargs_in->screen);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ecall_eat_gold_protected(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters */
    eat_gold_protected_args_t* pargs_in = (eat_gold_protected_args_t*) input_buffer;
    eat_gold_protected_args_t* pargs_out = (eat_gold_protected_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers */
    OE_SET_IN_OUT_POINTER(snake, sizeof(snake_t));
    OE_SET_IN_OUT_POINTER(screen, sizeof(screen_t));

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */
    OE_COPY_AND_SET_IN_OUT_POINTER(snake, sizeof(snake_t));
    OE_COPY_AND_SET_IN_OUT_POINTER(screen, sizeof(screen_t));

    /* Check that in/in-out strings are null terminated */

    /* lfence after checks */
    oe_lfence();

    /* Call user function */
    pargs_out->_retval = eat_gold_protected(
        pargs_in->snake,
        pargs_in->screen);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}



/****** ECALL function table  *************/
oe_ecall_func_t __oe_ecalls_table[] = {
    (oe_ecall_func_t) ecall_setup_level_protected,
    (oe_ecall_func_t) ecall_move_protected,
    (oe_ecall_func_t) ecall_collide_object_protected,
    (oe_ecall_func_t) ecall_collision_protected,
    (oe_ecall_func_t) ecall_eat_gold_protected,
};

size_t __oe_ecalls_table_size = OE_COUNTOF(__oe_ecalls_table);


/* ocall wrappers */

oe_result_t show_score_app(
        screen_t* screen)
{
    oe_result_t _result = OE_FAILURE;

    /* If the enclave is in crashing/crashed status, new OCALL should fail
       immediately. */
    if (oe_get_enclave_status() != OE_OK)
        return oe_get_enclave_status();

    /* Marshalling struct */ 
    show_score_app_args_t _args, *_pargs_in = NULL, *_pargs_out=NULL;

    /* Marshalling buffer and sizes */ 
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;
    size_t _output_bytes_written = 0;

    /* Fill marshalling struct */
    memset(&_args, 0, sizeof(_args));
    _args.screen = (screen_t*) screen;

    /* Compute input buffer size. Include in and in-out parameters. */
    OE_ADD_SIZE(_input_buffer_size, sizeof(show_score_app_args_t));
    if (screen) OE_ADD_SIZE(_input_buffer_size, sizeof(screen_t));

    /* Compute output buffer size. Include out and in-out parameters. */
    OE_ADD_SIZE(_output_buffer_size, sizeof(show_score_app_args_t));
    if (screen) OE_ADD_SIZE(_output_buffer_size, sizeof(screen_t));

    /* Allocate marshalling buffer */
    _total_buffer_size = _input_buffer_size;
    OE_ADD_SIZE(_total_buffer_size, _output_buffer_size);

    _buffer = (uint8_t*) oe_allocate_ocall_buffer(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL) { 
        _result = OE_OUT_OF_MEMORY;
        goto done;
    }

    /* Serialize buffer inputs (in and in-out parameters) */
    *(uint8_t**)&_pargs_in = _input_buffer; 
    OE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));

    OE_WRITE_IN_OUT_PARAM(screen, sizeof(screen_t));

    /* Copy args structure (now filled) to input buffer */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call host function */
    if((_result = oe_call_host_function(
                        fcn_id_show_score_app,
                        _input_buffer, _input_buffer_size,
                        _output_buffer, _output_buffer_size,
                         &_output_bytes_written)) != OE_OK)
        goto done;

    /* Set up output arg struct pointer */
    *(uint8_t**)&_pargs_out = _output_buffer; 
    OE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));

    /* Check if the call succeeded */
    if ((_result=_pargs_out->_result) != OE_OK)
        goto done;

    /* Currently exactly _output_buffer_size bytes must be written */
    if (_output_bytes_written != _output_buffer_size) {
        _result = OE_FAILURE;
        goto done;
    }

    /* Unmarshal return value and out, in-out parameters */
    OE_READ_IN_OUT_PARAM(screen, (size_t)(sizeof(screen_t)));

    _result = OE_OK;
done:    
    if (_buffer)
        oe_free_ocall_buffer(_buffer);
    return _result;
}

oe_result_t draw_line_app(
        int col,
        int row)
{
    oe_result_t _result = OE_FAILURE;

    /* If the enclave is in crashing/crashed status, new OCALL should fail
       immediately. */
    if (oe_get_enclave_status() != OE_OK)
        return oe_get_enclave_status();

    /* Marshalling struct */ 
    draw_line_app_args_t _args, *_pargs_in = NULL, *_pargs_out=NULL;

    /* Marshalling buffer and sizes */ 
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;
    size_t _output_bytes_written = 0;

    /* Fill marshalling struct */
    memset(&_args, 0, sizeof(_args));
    _args.col = col;
    _args.row = row;

    /* Compute input buffer size. Include in and in-out parameters. */
    OE_ADD_SIZE(_input_buffer_size, sizeof(draw_line_app_args_t));

    /* Compute output buffer size. Include out and in-out parameters. */
    OE_ADD_SIZE(_output_buffer_size, sizeof(draw_line_app_args_t));

    /* Allocate marshalling buffer */
    _total_buffer_size = _input_buffer_size;
    OE_ADD_SIZE(_total_buffer_size, _output_buffer_size);

    _buffer = (uint8_t*) oe_allocate_ocall_buffer(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL) { 
        _result = OE_OUT_OF_MEMORY;
        goto done;
    }

    /* Serialize buffer inputs (in and in-out parameters) */
    *(uint8_t**)&_pargs_in = _input_buffer; 
    OE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));


    /* Copy args structure (now filled) to input buffer */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call host function */
    if((_result = oe_call_host_function(
                        fcn_id_draw_line_app,
                        _input_buffer, _input_buffer_size,
                        _output_buffer, _output_buffer_size,
                         &_output_bytes_written)) != OE_OK)
        goto done;

    /* Set up output arg struct pointer */
    *(uint8_t**)&_pargs_out = _output_buffer; 
    OE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));

    /* Check if the call succeeded */
    if ((_result=_pargs_out->_result) != OE_OK)
        goto done;

    /* Currently exactly _output_buffer_size bytes must be written */
    if (_output_bytes_written != _output_buffer_size) {
        _result = OE_FAILURE;
        goto done;
    }

    /* Unmarshal return value and out, in-out parameters */

    _result = OE_OK;
done:    
    if (_buffer)
        oe_free_ocall_buffer(_buffer);
    return _result;
}

OE_EXTERNC_END
