/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_SGX_T_H
#define EDGER8R_SGX_T_H

#include <openenclave/enclave.h>
#include "sgx_args.h"

OE_EXTERNC_BEGIN

/* List of ecalls */

void setup_level_protected(screen_t* screen,
        snake_t* snake,
        int level);
void move_protected(snake_t* snake,
        char* keys,
        char key);
int collide_object_protected(snake_t* snake,
        screen_t* screen,
        char object);
int collision_protected(snake_t* snake,
        screen_t* screen);
int eat_gold_protected(snake_t* snake,
        screen_t* screen);

/* List of ocalls */

oe_result_t show_score_app(
        screen_t* screen);
oe_result_t draw_line_app(
        int col,
        int row);

OE_EXTERNC_END

#endif // EDGER8R_SGX_T_H
