/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#include "snake_t.h"
#include <openenclave/edger8r/enclave.h>
#include <stdlib.h>
#include <string.h>
#include <wchar.h>

OE_EXTERNC_BEGIN



/****** ECALL function wrappers  *************/
void ecall_eat_gold(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters */
    eat_gold_args_t* pargs_in = (eat_gold_args_t*) input_buffer;
    eat_gold_args_t* pargs_out = (eat_gold_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers */
    OE_SET_IN_OUT_POINTER(snake, sizeof(snake_t));
    OE_SET_IN_OUT_POINTER(screen, sizeof(screen_t));

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */
    OE_COPY_AND_SET_IN_OUT_POINTER(snake, sizeof(snake_t));
    OE_COPY_AND_SET_IN_OUT_POINTER(screen, sizeof(screen_t));

    /* Check that in/in-out strings are null terminated */

    /* lfence after checks */
    oe_lfence();

    /* Call user function */
    pargs_out->_retval = eat_gold(
        pargs_in->snake,
        pargs_in->screen);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}



/****** ECALL function table  *************/
oe_ecall_func_t __oe_ecalls_table[] = {
    (oe_ecall_func_t) ecall_eat_gold,
};

size_t __oe_ecalls_table_size = OE_COUNTOF(__oe_ecalls_table);

OE_EXTERNC_END
