/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_SNAKE_T_H
#define EDGER8R_SNAKE_T_H

#include <openenclave/enclave.h>
#include "snake_args.h"

OE_EXTERNC_BEGIN

/* List of ecalls */

int eat_gold(snake_t* snake,
        screen_t* screen);

OE_EXTERNC_END

#endif // EDGER8R_SNAKE_T_H
